import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.bundle.min';
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
import App from "./components/App";
import store from './redux/store';
import {BrowserRouter as Router, Route} from 'react-router-dom';

//(DONE) SET UP REDUX AND REDUX THUNK
//(DONE) BUILD GOOGLE LOGIN BUTTON
//(DONE) BUILD NAV BAR AND CLOSING / OPENING
//(DONE) STYLE GOOGLE LOGIN BUTTON
//(DONE) CREATE LOADER STATE
//(DONE) SHOW USER'S NAME ONCE LOGGED
//(DONE) REMOVE EXTRA REDUCERS AND PASS IN VARIABLES
//(DONE) CREATE RESPONSIVE LEFT NAV
//(DONE) CHANGE STATES IN GOOGLEBTN TO REDUX
//(DONE) SPLIT FILES INTO DIFFERENT COMPONENTS
//(DONE) SETUP JSON SERVER
//(DONE) ADD USER TO DB ONCE LOGGED IN
//(DONE) FIXED NAV POSITION FIXED
//(DONE) CHECK IF SERVER IS ONLINE ONCE LOGGED IN
//(DONE) ADD CHART.JS + REACT-CHARTJS-2
//(DONE) FIX NAV BUTTON
//(DONE) BUILD RESPONSIVE BITCOIN CHART
//(DONE) CREATE DASHBOARD UI
//(DONE) RESPONSIVE DASHBOARD UI
//(DONE) BUILD LOADERS, ACTIONS, AND STORES FOR FAVORITES
//(DONE) LOGIN TO SAVE FAVORITES
//(DONE) BUILD RESPONSIVE FAVORITES UI
//(DONE) RESPONSIVE SCROLL BAR
//(DONE) SHOW FAVORITES CHARTS ON LOGIN
//(DONE) FIX GOOGLE BUTTON RESPONSIVE
//(DONE) ADD (DONE) / REMOVE FAVORITES
//(DONE) HIDE REMOVE FAVORITE BUTTON WHEN NOT LOGGED IN
//(DONE) RESPONSIVE FAVORITES LIST BUTTONS
//(DONE) NEXT / BACK FAVORITES LIST BUTTONS
//(DONE) ADD PLACEHOLDER GRAPHS WHEN NOT LOGGED IN
//(DONE) CHANGE GRADIENTS OF GRAPHS
//(DONE) CONNECT BITCOIN TO COINGECKO API
//() CONNECT FAVORITES TO COINGECKO API
//() CONNECT TRENDING TO COINGECKO API
//() CONNECT CHANGES TO COINGECKO API
//() PRICES OR COINS LIST LINK (PRICES OF EACH CURRENT AND COIN)
//() EVENTS LINK
//() EXCHANGES LINK
//() NEWS API
//() (OPTIONAL) BUILD BITCOIN DROPDOWN CHART CHANGES

ReactDOM.render(
    <Router>
        <Provider store={store}>
            <Route exact path="/">
                <App />
            </Route>
        </Provider>
    </Router>, 
    document.querySelector("#root")
);
